### ISSUE TITLE
Error syncing to Glitch: Incorrect statusCode: 503

### ISSUE THREAD

**Issue by iwiedenm** [kanadgupta/glitch-sync#11]
When pushing to GitHub the action fails with this message: "Error syncing to Glitch: Incorrect statusCode: 503"

**Comment by kanadgupta** [comment]
I believe that's an issue with the Glitch API. What happens when you [re-run the workflow](https://docs.github.com/en/actions/managing-workflow-runs/re-running-a-workflow)?

**Comment by iwiedenm** [comment]
I re-ran it a few times without success but it eventually fixed itself. Probably an issue with Glitch.

**Comment by kanadgupta** [comment]
Yeah a 503 is an issue with the Glitch API. Glad you got it figured out!
