### ISSUE TITLE
Add capability to push to glitch a specific repository

### ISSUE THREAD

**Issue by abenevaut** [kanadgupta/glitch-sync#6]
Hello! Thanks for your time applied to this tool.

Could you please add the functionality to be able to specify a specific directory (one more env var to the action) from my github repository to be published to the glitch git repository ?

**Comment by kanadgupta** [comment]
Thanks for reaching out and for your interest in this tool, @abenevaut! Just shipped [`v1.1`](https://github.com/kanadgupta/glitch-sync/releases/tag/v1.1), which includes support for specifying a directory.

Apologies for the delay on this. Happy holidays!
